version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "/Users/admin/CommonProjects/local-kafka/data/zk:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "19092:19092"
      - "19093:19093"
      - "19094:19094"
    volumes:
      - "/Users/admin/CommonProjects/local-kafka/data/b1:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,CONTROLLER://:19093,EXTERNAL://:19094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:19092,EXTERNAL://localhost:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
  kafka2:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "29092:29092"
      - "29093:29093"
      - "29094:29094"
    volumes:
      - "/Users/admin/CommonProjects/local-kafka/data/b2:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:29092,EXTERNAL://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - kafka1
  kafka3:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "39092:39092"
      - "39093:39093"
      - "39094:39094"
    volumes:
      - "/Users/admin/CommonProjects/local-kafka/data/b3:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:39092,CONTROLLER://:39093,EXTERNAL://:39094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:39092,EXTERNAL://localhost:39094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - kafka2
  kafka4:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "49092:49092"
      - "49093:49093"
      - "49094:49094"
    volumes:
      - "/Users/admin/CommonProjects/local-kafka/data/b4:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:49092,CONTROLLER://:49093,EXTERNAL://:49094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka4:49092,EXTERNAL://localhost:49094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - kafka3
